"""add compound indexes to businesses

Revision ID: f1cbd84cb5d6
Revises: 0008_biz_leads
Create Date: 2026-02-22 18:59:34.223047
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1cbd84cb5d6'
down_revision = '0008_biz_leads'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('businesses_name_score_idx', 'businesses', ['name', 'lead_score'], unique=False)
    op.create_index('businesses_website_score_idx', 'businesses', ['website_url', 'lead_score'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('businesses_website_score_idx', table_name='businesses')
    op.drop_index('businesses_name_score_idx', table_name='businesses')
    # ### end Alembic commands ###
