"""restore missing indexes

Revision ID: da271bac25f9
Revises: f1cbd84cb5d6
Create Date: 2026-02-22 19:01:00.889869
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da271bac25f9'
down_revision = 'f1cbd84cb5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use if_not_exists=True to prevent crashes when indexes already exist
    # from earlier migrations (safe for both fresh and existing databases).
    op.create_index('business_outreach_exports_platform_status_idx', 'business_outreach_exports', ['platform', 'status'], unique=False, if_not_exists=True)
    op.create_index('businesses_city_idx', 'businesses', ['city_id'], unique=False, if_not_exists=True)
    op.create_index('businesses_lead_score_idx', 'businesses', ['lead_score'], unique=False, if_not_exists=True)

    # Unique constraint — check if it exists before creating
    from sqlalchemy import inspect as sa_inspect
    bind = op.get_bind()
    inspector = sa_inspect(bind)
    existing_ucs = [uc["name"] for uc in inspector.get_unique_constraints("businesses")]
    if "businesses_source_uidx" not in existing_ucs:
        op.create_unique_constraint('businesses_source_uidx', 'businesses', ['source', 'source_id'])

    op.create_index('cities_name_idx', 'cities', ['name'], unique=False, if_not_exists=True)
    op.create_index('contacts_email_idx', 'contacts', ['email'], unique=False, if_not_exists=True)
    op.create_index('contacts_lead_score_idx', 'contacts', ['lead_score'], unique=False, if_not_exists=True)
    op.create_index('domains_status_idx', 'domains', ['status'], unique=False, if_not_exists=True)
    op.create_index('domaintools_domain_idx', 'domaintools_checks', ['domain_id'], unique=False, if_not_exists=True)
    op.create_index('whois_domain_idx', 'whois_checks', ['domain_id'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('whois_domain_idx', table_name='whois_checks')
    op.drop_index('domaintools_domain_idx', table_name='domaintools_checks')
    op.drop_index('domains_status_idx', table_name='domains')
    op.drop_index('contacts_lead_score_idx', table_name='contacts')
    op.drop_index('contacts_email_idx', table_name='contacts')
    op.drop_index('cities_name_idx', table_name='cities')
    op.drop_constraint('businesses_source_uidx', 'businesses', type_='unique')
    op.drop_index('businesses_lead_score_idx', table_name='businesses')
    op.drop_index('businesses_city_idx', table_name='businesses')
    op.drop_index('business_outreach_exports_platform_status_idx', table_name='business_outreach_exports')
    # ### end Alembic commands ###
